# -*- coding: utf-8 -*-
"""01_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNDxAXjhzGfklJ-it_QCtqDjVEu3Ss6X
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from scipy.interpolate import griddata
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from google.colab import files
import subprocess
import os

# ===== INSTALL TIMES NEW ROMAN FONT =====
print("Installing Times New Roman font...")
try:
    subprocess.run(['apt-get', 'install', '-y', 'msttcorefonts', '-qq'],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    # Remove matplotlib font cache
    subprocess.run(['rm', '-rf', os.path.expanduser('~/.cache/matplotlib')],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print("✓ Font installation complete")
except:
    print("Note: Using default serif font")

# Set font to Times New Roman
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman', 'DejaVu Serif', 'Liberation Serif']
plt.rcParams['mathtext.fontset'] = 'stix'

# ===== INPUT PARAMETERS =====
print("=" * 60)
print("PULTRUSION PARAMETRIC STUDY DATA PROCESSOR")
print("=" * 60)

# Get velocity range
vel_min = float(input("\nEnter minimum velocity (m/min): "))
vel_max = float(input("Enter maximum velocity (m/min): "))
vel_step = float(input("Enter velocity step (m/min): "))

# Get temperature range
temp_min = float(input("\nEnter minimum die temperature (°C): "))
temp_max = float(input("Enter maximum die temperature (°C): "))
temp_step = float(input("Enter temperature step (°C): "))

# Generate parameter arrays
velocities = np.arange(vel_min, vel_max + vel_step/2, vel_step)
temperatures = np.arange(temp_min, temp_max + temp_step/2, temp_step)

print(f"\nVelocities: {velocities}")
print(f"Temperatures: {temperatures}")
print(f"Total number of cases: {len(velocities) * len(temperatures)}")

# ===== UPLOAD FILES =====
print("\n" + "=" * 60)
print("Please upload the 'cure' file:")
uploaded_cure = files.upload()
cure_filename = list(uploaded_cure.keys())[0]

print("\nPlease upload the 'temperature' file:")
uploaded_temp = files.upload()
temp_filename = list(uploaded_temp.keys())[0]

# ===== PROCESS CURE DATA =====
print("\n" + "=" * 60)
print("Processing cure data...")

# Read the cure file
cure_data = pd.read_csv(cure_filename, sep=r'\s+', header=None, names=['Axial_Distance', 'Cure_Degree'])

# Determine number of points per case (assuming distance goes from 0 to 1000)
axial_distances = cure_data['Axial_Distance'].values
# Find where the pattern repeats (when distance resets)
reset_indices = np.where(np.diff(axial_distances) < 0)[0] + 1
if len(reset_indices) > 0:
    points_per_case = reset_indices[0]
else:
    points_per_case = len(axial_distances)

print(f"Points per case: {points_per_case}")

# Create organized cure dataframe
cure_organized = pd.DataFrame()
cure_organized['Axial_Distance'] = axial_distances[:points_per_case]

case_idx = 0
for vel in velocities:
    for temp in temperatures:
        start_idx = case_idx * points_per_case
        end_idx = start_idx + points_per_case
        col_name = f'V={vel:.2f}_T={temp:.0f}'
        cure_organized[col_name] = cure_data['Cure_Degree'].values[start_idx:end_idx]
        case_idx += 1

# ===== PROCESS TEMPERATURE DATA =====
print("Processing temperature data...")

# Read the temperature file
temp_data = pd.read_csv(temp_filename, sep=r'\s+', header=None, names=['Axial_Distance', 'Die_Temperature'])

# Create organized temperature dataframe
temp_organized = pd.DataFrame()
temp_organized['Axial_Distance'] = axial_distances[:points_per_case]

case_idx = 0
for vel in velocities:
    for temp in temperatures:
        start_idx = case_idx * points_per_case
        end_idx = start_idx + points_per_case
        col_name = f'V={vel:.2f}_T={temp:.0f}'
        temp_organized[col_name] = temp_data['Die_Temperature'].values[start_idx:end_idx]
        case_idx += 1

# ===== CREATE SUMMARY DATAFRAME =====
print("Creating summary statistics...")

summary_data = []
for vel in velocities:
    for temp in temperatures:
        col_name = f'V={vel:.2f}_T={temp:.0f}'

        # Final cure degree at 1000mm (last value)
        final_cure = cure_organized[col_name].iloc[-1]

        # Maximum temperature along the die
        max_temp = temp_organized[col_name].max()

        summary_data.append({
            'Velocity (m/min)': vel,
            'Die Temperature (°C)': temp,
            'Final Cure Degree at 1000mm': final_cure,
            'Maximum Temperature (°C)': max_temp
        })

summary_df = pd.DataFrame(summary_data)

# ===== EXPORT TO EXCEL =====
print("Exporting to Excel...")

with pd.ExcelWriter('pultrusion_results.xlsx', engine='openpyxl') as writer:
    # Sheet 1: Summary
    summary_df.to_excel(writer, sheet_name='Summary', index=False)

    # Sheet 2: Cure Data
    cure_organized.to_excel(writer, sheet_name='Cure_Degree', index=False)

    # Sheet 3: Temperature Data
    temp_organized.to_excel(writer, sheet_name='Die_Temperature', index=False)

# Format the Excel file
wb = openpyxl.load_workbook('pultrusion_results.xlsx')
ws_summary = wb['Summary']

# Format headers
header_fill = PatternFill(start_color='366092', end_color='366092', fill_type='solid')
header_font = Font(bold=True, color='FFFFFF')

for cell in ws_summary[1]:
    cell.fill = header_fill
    cell.font = header_font
    cell.alignment = Alignment(horizontal='center', vertical='center')

# Auto-adjust column widths
for column in ws_summary.columns:
    max_length = 0
    column = [cell for cell in column]
    for cell in column:
        try:
            if len(str(cell.value)) > max_length:
                max_length = len(cell.value)
        except:
            pass
    adjusted_width = (max_length + 2)
    ws_summary.column_dimensions[column[0].column_letter].width = adjusted_width

wb.save('pultrusion_results.xlsx')

print("Excel file 'pultrusion_results.xlsx' created successfully!")

# ===== CREATE DESIGN CHARTS =====
print("\nCreating high-resolution design charts for publication...")

# Prepare data for contour plots
vel_grid, temp_grid = np.meshgrid(velocities, temperatures)

# Reshape data for plotting
cure_matrix = summary_df['Final Cure Degree at 1000mm'].values.reshape(len(velocities), len(temperatures)).T
temp_max_matrix = summary_df['Maximum Temperature (°C)'].values.reshape(len(velocities), len(temperatures)).T

# Determine contour levels for cure degree (0.001 step)
cure_min = cure_matrix.min()
cure_max = cure_matrix.max()
cure_levels_contour = np.arange(np.floor(cure_min * 1000) / 1000,
                                 np.ceil(cure_max * 1000) / 1000 + 0.001,
                                 0.001)

# Create figure with two subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 7))

# Plot 1: Final Cure Degree
contour1 = ax1.contourf(vel_grid, temp_grid, cure_matrix, levels=50, cmap='RdYlGn')
#contour1_lines = ax1.contour(vel_grid, temp_grid, cure_matrix, levels=cure_levels_contour,
#                              colors='black', linewidths=0.8, alpha=0.6)
contour1_lines = ax1.contour(vel_grid, temp_grid, cure_matrix, levels=15,
                              colors='black', linewidths=0.8, alpha=0.6)
ax1.clabel(contour1_lines, inline=True, fontsize=9, fmt='%.3f', inline_spacing=8)
cbar1 = plt.colorbar(contour1, ax=ax1, format='%.3f')
cbar1.set_label('Final Cure Degree', rotation=270, labelpad=25, fontsize=13)
cbar1.ax.tick_params(labelsize=11)
ax1.set_xlabel('Velocity (m/min)', fontsize=14)
ax1.set_ylabel('Die Temperature (°C)', fontsize=14)
ax1.set_title('Final Cure Degree at 1000mm', fontsize=15, pad=20)
ax1.tick_params(axis='both', which='major', labelsize=12)
ax1.grid(True, alpha=0.2, linestyle='--', linewidth=0.5)

# Plot 2: Maximum Temperature
contour2 = ax2.contourf(vel_grid, temp_grid, temp_max_matrix, levels=50, cmap='hot_r')
contour2_lines = ax2.contour(vel_grid, temp_grid, temp_max_matrix, levels=15,
                              colors='black', linewidths=0.8, alpha=0.6)
ax2.clabel(contour2_lines, inline=True, fontsize=9, fmt='%.1f', inline_spacing=8)
cbar2 = plt.colorbar(contour2, ax=ax2, format='%.1f')
cbar2.set_label('Maximum Temperature (°C)', rotation=270, labelpad=25, fontsize=13)
cbar2.ax.tick_params(labelsize=11)
ax2.set_xlabel('Velocity (m/min)', fontsize=14)
ax2.set_ylabel('Die Temperature (°C)', fontsize=14)
ax2.set_title('Maximum Temperature Along Die', fontsize=15, pad=20)
ax2.tick_params(axis='both', which='major', labelsize=12)
ax2.grid(True, alpha=0.2, linestyle='--', linewidth=0.5)

plt.tight_layout()
plt.savefig('design_charts_publication.png', dpi=600, bbox_inches='tight', facecolor='white')
plt.savefig('design_charts_publication.pdf', dpi=600, bbox_inches='tight', facecolor='white')
plt.savefig('design_charts_publication.eps', dpi=600, bbox_inches='tight', facecolor='white')
plt.show()

print("High-resolution design charts saved:")
print("  - design_charts_publication.png (600 dpi)")
print("  - design_charts_publication.pdf (vector)")
print("  - design_charts_publication.eps (vector)")

# ===== CREATE 3D SURFACE PLOTS =====
print("\nCreating high-resolution 3D surface plots...")

fig = plt.figure(figsize=(18, 7))

# 3D plot 1: Final Cure Degree
ax1 = fig.add_subplot(121, projection='3d')
surf1 = ax1.plot_surface(vel_grid, temp_grid, cure_matrix, cmap='RdYlGn',
                          edgecolor='none', alpha=0.95, antialiased=True,
                          linewidth=0, shade=True)
ax1.set_xlabel('Velocity (m/min)', fontsize=13, labelpad=10)
ax1.set_ylabel('Die Temperature (°C)', fontsize=13, labelpad=10)
ax1.set_zlabel('Final Cure Degree', fontsize=13, labelpad=10)
ax1.set_title('Final Cure Degree at 1000mm', fontsize=15, pad=20)
ax1.tick_params(axis='both', which='major', labelsize=11)
ax1.view_init(elev=25, azim=45)
cbar1 = fig.colorbar(surf1, ax=ax1, shrink=0.6, aspect=10, pad=0.1, format='%.3f')
cbar1.ax.tick_params(labelsize=10)

# 3D plot 2: Maximum Temperature
ax2 = fig.add_subplot(122, projection='3d')
surf2 = ax2.plot_surface(vel_grid, temp_grid, temp_max_matrix, cmap='hot_r',
                          edgecolor='none', alpha=0.95, antialiased=True,
                          linewidth=0, shade=True)
ax2.set_xlabel('Velocity (m/min)', fontsize=13, labelpad=10)
ax2.set_ylabel('Die Temperature (°C)', fontsize=13, labelpad=10)
ax2.set_zlabel('Maximum Temperature (°C)', fontsize=13, labelpad=10)
ax2.set_title('Maximum Temperature Along Die', fontsize=15, pad=20)
ax2.tick_params(axis='both', which='major', labelsize=11)
ax2.view_init(elev=25, azim=45)
cbar2 = fig.colorbar(surf2, ax=ax2, shrink=0.6, aspect=10, pad=0.1, format='%.1f')
cbar2.ax.tick_params(labelsize=10)

plt.tight_layout()
plt.savefig('design_charts_3d_publication.png', dpi=600, bbox_inches='tight', facecolor='white')
plt.savefig('design_charts_3d_publication.pdf', dpi=600, bbox_inches='tight', facecolor='white')
plt.savefig('design_charts_3d_publication.eps', dpi=600, bbox_inches='tight', facecolor='white')
plt.show()

print("High-resolution 3D charts saved:")
print("  - design_charts_3d_publication.png (600 dpi)")
print("  - design_charts_3d_publication.pdf (vector)")
print("  - design_charts_3d_publication.eps (vector)")

# ===== SUMMARY =====
print("\n" + "=" * 60)
print("PROCESSING COMPLETE!")
print("=" * 60)
print("\nGenerated files:")
print("\n📊 Excel File:")
print("  • pultrusion_results.xlsx")
print("\n📈 2D Contour Plots (Publication Quality - 600 DPI):")
print("  • design_charts_publication.png")
print("  • design_charts_publication.pdf (vector)")
print("  • design_charts_publication.eps (vector)")
print("\n📉 3D Surface Plots (Publication Quality - 600 DPI):")
print("  • design_charts_3d_publication.png")
print("  • design_charts_3d_publication.pdf (vector)")
print("  • design_charts_3d_publication.eps (vector)")
print("\n" + "=" * 60)
print("Files are ready in your Colab environment.")
print("Access them from the Files panel on the left.")
print("PDF and EPS formats are vector graphics, ideal for journals.")
print("=" * 60)